/*
 *
 * Crowdsale constants
 *
 */

export const LOAD_CROWDSALE_TRANSACTIONS =
  'OmniXEP-explorer/App/LOAD_CROWDSALE_TRANSACTIONS';
export const LOAD_CROWDSALE_TRANSACTIONS_SUCCESS =
  'OmniXEP-explorer/App/LOAD_CROWDSALE_TRANSACTIONS_SUCCESS';
export const LOAD_CROWDSALE_TRANSACTIONS_CANCEL =
  'OmniXEP-explorer/App/LOAD_CROWDSALE_TRANSACTIONS_CANCEL';
export const SET_CROWDSALES_TRANSACTIONS_PAGE =
  'OmniXEP-explorer/App/SET_CROWDSALES_TRANSACTIONS_PAGE';
